language: node_js
node_js:
  - "0.10"
  - "4"
  - "node"
services:
  - redis-server
before_install:
  - if [[ `node --version` =~ "v0.10" ]]; then npm install -g npm@latest; fi
  - npm config set spin false
  - printf "@npm:registry=https://registry.internal.npmjs.com/\n//registry.internal.npmjs.com/:_authToken=${NPM_TOKEN}\n" >> ~/.npmrc
